name: Build & Deploy to Test

on:
  push:
    branches:
      - test
    paths:
      - 'src/**'
      - 'public/**'
      - 'sitemap-generator.js'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.*'
      - 'tsconfig*.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set Build ENV variable
        run: echo "VITE_BUILD_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Set GA4 Measurement ID
        run: echo "VITE_GA4_MEASUREMENT_ID=${{ secrets.GA4_MEASUREMENT_ID }}" >> $GITHUB_ENV

      - name: Build
        run: npm run build

      - name: Deploy to Firebase charlie channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRIVERSE_E5CE1 }}
          projectId: triverse-e5ce1
          channelId: charlie
